project_id = "ozgfjntbxogdgyjvsvha"

[functions.jkkn-chat]
verify_jwt = false

[functions.career-assessment]
verify_jwt = true

[functions.admin-setup]
verify_jwt = false

[functions.student-assessment]
verify_jwt = true
